import Head from "next/head";
import Art from "../components/Art/Art";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.title}>
          Welcome to the <a>Gallery!</a>
        </h1>
        <Art
          src="/art/FaceIt.jpg"
          title="Face It"
          description="Created in Krita."
        ></Art>
      </main>
    </div>
  );
}
